[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip R7FA4M1AB --protocol swd --speed 4000"

rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
